# Netlify Configuration for Chris Nattress Portfolio
# Next.js 15 App Router with AI Integration

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Development settings for Netlify CLI
[dev]
  command = "npm run dev"
  port = 3000
